const { create } = require("zustand");

const useProductStore = create(() => ({
  products: [
    {
      id: 1,
      img: "/assets/products/newDawn.png",
      path: "new-dawn",
      status: "new",
      price: { original: 30000, discount: false },
      category: "sweatshirts",
      colors: ["white", "black"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 2,
      img: "/assets/products/theRitual.png",
      path: "the-ritual",
      status: "new",
      price: { original: 35000, discount: 20000 },
      category: "shirts",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 3,
      img: "/assets/products/toteBag.png",
      path: "tote-bag",
      status: "new",
      price: { original: 25000, discount: false },
      category: "bags",
      colors: ["black"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 4,
      img: "/assets/products/artBag.png",
      path: "art-bag",
      status: "",
      price: { original: 30000, discount: 25000 },
      category: "bags",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 5,
      img: "/assets/products/ayeSayPal(calmEdition).png",
      path: "aye-say-pal-sweatshirt",
      status: "",
      price: { original: 35000, discount: false },
      category: "sweatshirts",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 6,
      img: "/assets/products/ayeSayPal(original).png",
      path: "aye-say-pal-hoodies",
      status: "",
      price: { original: 40000, discount: false },
      category: "hoodies",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 7,
      img: "/assets/products/livingNightmare.png",
      path: "living-nightmare",
      status: "",
      price: { original: 30000, discount: false },
      category: "shirts",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 8,
      img: "/assets/products/pufferJacket.png",
      path: "puffer-jacket",
      status: "",
      price: { original: 35000, discount: false },
      category: "jackets",
      colors: ["black"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 9,
      img: "/assets/products/bennie.png",
      path: "bennie",
      status: "",
      price: { original: 40000, discount: false },
      category: "caps",
      colors: ["yellow"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 10,
      img: "/assets/products/toteBag2.png",
      path: "tote-bag-2",
      status: "new",
      price: { original: 35000, discount: false },
      category: "bags",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 11,
      img: "/assets/products/sunsetVibe.png",
      path: "sunset-vibe",
      status: "new",
      price: { original: 30000, discount: false },
      category: "shirts",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 12,
      img: "/assets/products/chillModeGraphicTee.png",
      path: "chill-mode-graphic-tee",
      status: "",
      price: { original: 30000, discount: false },
      category: "shirts",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 13,
      img: "/assets/products/classicComfortShirt.png",
      path: "classic-comfort-shirt",
      status: "",
      price: { original: 40000, discount: false },
      category: "shirts",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 14,
      img: "/assets/products/boldVibeTee.png",
      path: "bold-vibes-tee",
      status: "",
      price: { original: 35000, discount: false },
      category: "shirts",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 15,
      img: "/assets/products/urbanLegendsTee.png",
      path: "urban-legends-tee",
      status: "",
      price: { original: 35000, discount: false },
      category: "shirts",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
    {
      id: 16,
      img: "/assets/products/ayeSayPal(shirt).png",
      path: "aye-say-pal-shirt",
      status: "",
      price: { original: 35000, discount: false },
      discount: false,
      category: "shirts",
      colors: ["white"],
      sizes: ["S", "M", "L", "XL"],
      description:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Harum minima similique voluptates.",
    },
  ],
}));

export default useProductStore;
